### PR TITLE
Merge pull request #3 from adarshrwl/firebase

### PR DESCRIPTION
**Pull request by adarshrwl**
Minour changes

### CODE REVIEW

**Comment by Ansaldude** [comment]
Ansal .

**Comment by Ansaldude** [comment]
done

**Comment by divashbh** [comment]
ok done

**Comment by DEEPAKSAPKOTA4582** [comment]
Ok Done

**Comment by Ansaldude** [comment]
ok done

**Comment by Ansaldude** [comment]
good

**Pull request merged**
